version: '3.8'

networks:
  opensearch-net:
    driver: bridge

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    networks:
      - opensearch-net
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ports:
      - "9200:9200"
      - "9600:9600"
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    networks:
      - opensearch-net
    env_file:
      - .env
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200
      - OPENSEARCH_DASHBOARDS_SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

